name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install node js by command install or CI
        run: npm ci 
      - run: npm run format:check
      - run: npm text -- --coverage
        with:
          CI: true